language: go
os:
  - linux
  - osx
go:
  - 1.13.x
go_import_path: github.com/kataras/versioning
env:
 global:
   - GO111MODULE=on
install:
  - go get ./...
script:
  - go test -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../
